name: analytics
version: 1.0.0-dev.1
description: |
  Interface for working with analytic services. The library is supposed to unify work with various analytic services.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/analytics"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  logger: ^1.0.0

dev_dependencies:
  surf_lint_rules: ^1.0.0
  test: ^1.17.2

environment:
  sdk: ">=2.12.0 <3.0.0"
