name: flutter_template
description: a Flutter Template project for development.

version: 0.0.1-rc1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #внутренние библиотеки
  network:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: dev
      path: network
  logger:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: dev
      path: logger
  injector:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: dev
      path: injector
  mwwm:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: dev
      path: mwwm

  intl: 0.15.7

  flutter_svg: 0.10.3
  qr_flutter: ^2.0.0

  #networking
  http: 0.12.0+1
  dio: 2.1.2

  #parsing
  json_annotation: 2.0.0

  #storage
  shared_preferences: 0.5.1+1
  path_provider: 0.5.0

  #rx
  rxdart: 0.21.0

  #crash reporting
  #firebase_crashlytics: ^0.0.4+1 need research about this
  flutter_crashlytics: 0.3.0 # newer version has a bug on ios or i have ruki iz zhopi

  #camera
  camera: 0.4.3+2

  #masked text
  flutter_masked_text: 0.8.0
  string_mask: 0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2

  #firebase push
  firebase_core: 0.3.1+1
  firebase_messaging: 4.0.0+1

  #firebase ml kit
  firebase_ml_vision: 0.6.0+2

  #notifications
  flutter_local_notifications: 0.6.0

  #connection
  connectivity: 0.4.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - res/assets/
