name: flutter_template
version: "0.0.1-dev.0"
description: a Flutter template project for development.
repository: https://github.com/surfstudio/SurfGear/tree/dev/packages/template

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  surf_network: ^0.0.1-dev.0
  surf_logger: ^0.0.1-dev.1
  surf_injector: ^0.0.1-dev.0
  surf_mwwm: ^0.0.1-dev.0
  geolocation:
    path: ../packages/geolocation
#    git:
#      url: "https://gitlab.com/surfstudio/public/flutter-standard.git"
#      path: packages/geolocation
  analytics: ^0.0.1-dev.0
  bottom_sheet: ^0.0.1-dev.0
  push_notification: ^0.0.1-dev.0
  surf_util: ^0.0.1-dev.0
  surf_lint_rules: ^0.0.1-dev.0
  intl: ^0.16.1
  flutter_svg: ^0.15.0
  http: ^0.12.0+4
  dio: ^3.0.8
  shared_preferences: 0.5.6+3
  path_provider: ^1.5.1
  rxdart: ^0.24.0
  firebase_crashlytics: ^0.1.2+4
  string_mask: ^0.1.0
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.6+2
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - res/assets/

custom:
  is_stable: false
  unstable_version: 1
  is_plugin: false
  path: template
  separate_repo_url:
  hostUrl:
