name: flutter_template
description: a Flutter Template project for development.

version: 0.0.1-rc1+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #внутренние библиотеки
  network:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: network
  logger:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: logger
  injector:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: injector
  mwwm:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: mwwm
  geolocation:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: geolocation
  analytics:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: analytics

  # модуль push уведомлений
  push:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: push
  surf_util:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: surf_util

  intl: ^0.15.7

  flutter_svg: ^0.14.1

  #networking
  http: ^0.12.0+1
  dio: ^2.1.2

  #storage
  shared_preferences: ^0.5.3+4
  path_provider: ^1.3.0

  #rx
  rxdart: 0.24.1

  #crash reporting
  firebase_crashlytics: ^0.1.0+3

  #masked text
  string_mask: ^0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #connection
  connectivity: ^0.4.4

  pedantic: ^1.8.0

  # testing mock
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/assets/
