name: example
description: Example using bottom sheet.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bottom_sheet:
    path: ../

  flutter:
    sdk: flutter

  rxdart: ^0.27.0

dev_dependencies:
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
