name: bottom_sheet
version: 1.0.1-dev.2
description: Flexible bottom sheet with the ability to scroll content even without a list.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/bottom_sheet"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: bottom_sheet
  separate_repo_url:
  hostUrl:
