name: push_notification
version: "0.0.1-dev.0"
description: A new Flutter plugin.

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.0
  surf_lint_rules:
    git:
      url: "https://gitlab.com/surfstudio/public/flutter-standard.git"
      path: packages/surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:
  plugin:
    androidPackage: pushnotification.push_notification
    pluginClass: PushNotificationPlugin

custom:
  is_stable: false
  unstable_version: 1
  is_plugin: true
  path: push_notification
  separate_repo_url:
  hostUrl:
