name: push_notification
version: 1.0.1-dev.1
description: Library for implementing push notifications. The module contains the main work with push notifications.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/push_notification"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: pushnotification.push_notification
        pluginClass: PushNotificationPlugin
      ios:
        pluginClass: PushNotificationPlugin
