name: render_metrics
version: "1.0.2-dev.4"
description: "Library for getting widget metrics. Uses RenderObject to get the size and position of widgets relative to the screen window, as well as the difference between widgets."
homepage: "https://github.com/surfstudio/render_metrics"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: "^0.0.1-dev.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: render_metrics
  separate_repo_url: "https://github.com/surfstudio/render_metrics"
  hostUrl:
