name: relation
description: the stream representation of the relations of the entities and widget utilities
version: 0.0.2
homepage: https://github.com/surfstudio/mwwm

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #rx
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.7.0

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: relation
  separate_repo_url:
  hostUrl:
