name: relation
description: the stream representation of the relations of the entities and widget utilities
version: 0.0.2
homepage: https://github.com/surfstudio/relation

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #rx
  rxdart: ^0.24.0

  surf_lint_rules:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      path: ../surf_lint_rules
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: relation
  separate_repo_url: https://github.com/surfstudio/relation
  hostUrl:
