name: build_context_holder
description: The BuildContext store received from the last created widget.
version: 0.0.1-dev.0
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: build_context_holder
  separate_repo_url:
  hostUrl:
