name: auto_reload
version: "0.0.1-dev.1"
description: a library that helps to perform actions with some periodicity
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/auto_reload"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.6+2
  surf_lint_rules: "^0.0.1-dev.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: auto_reload
  separate_repo_url:
  hostUrl:
