name: auto_reload
version: "0.0.1-dev.4"
description: a library that helps to perform actions with some periodicity
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/auto_reload"

dependencies:
  connectivity: ^2.0.0
  flutter:
    sdk: flutter
  surf_lint_rules: "^0.0.2-dev.5"

dev_dependencies:
  fake_async: ^1.1.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2

environment:
  sdk: ">=2.6.0 <3.0.0"

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: auto_reload
  separate_repo_url:
  hostUrl:
