name: event_filter
version: "0.1.0-dev.0"
description: Mecanism for filtering events.
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/event_filter"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: ^0.0.2-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: event_filter
  separate_repo_url:
  hostUrl:
