name: example
description: Example

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  surf_util:
    path: ..

  mwwm:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: project-ROS-28
      path: mwwm


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
