name: otp_autofill
version: "0.0.1-dev.2"
description: |
  Android implementation of OTP autofill with using User Consent API and Retriever API. Add possibility to receive OTP code from another input.
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules:
    path: ../surf_lint_rules

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.otp_autofill
        pluginClass: OTPPlugin
      ios:
        pluginClass: OTPPlugin

custom:
  is_stable: false
  unstable_version:
  is_plugin: true
  path: otp_autofill
  separate_repo_url:
  hostUrl:
