name: otp_autofill
version: 1.0.2
description: Android implementation of OTP autofill with using User Consent API and Retriever API. Add possibility to receive OTP code from another input.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/otp_autofill"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.otp_autofill
        pluginClass: OTPPlugin
      ios:
        pluginClass: OTPPlugin

custom:
  is_stable: false
  unstable_version:
  is_plugin: true
  path: otp_autofill
  separate_repo_url:
  hostUrl:

dependency_validator:
  exclude:
    - "example/**"
