name: example
description: Example of using event filter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  #rx
  rxdart: ^0.22.0

  #surfstudio
  injector:
    git:
      url: https://gitlab.com/builder-surf/flutter-standard.git
      ref: project-RIG-13
      path: injector

  mwwm:
    git:
      url: https://gitlab.com/builder-surf/flutter-standard.git
      ref: project-RIG-13
      path: mwwm

  relation:
    git:
      url: https://gitlab.com/builder-surf/flutter-standard.git
      ref: project-RIG-13
      path: relation

  event_filter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true