name: example
description: Example of using event filter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  #rx
  rxdart: ^0.22.0

  #surfstudio
  injector:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: PROJECT-ROS-33
      path: injector
  mwwm:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: PROJECT-ROS-33
      path: mwwm

  event_filter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true