name: otp_autofill_example
description: Demonstrates how to use the otp_autofill plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  otp_autofill:
    path: ../

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_lint_rules:
    path: ../../surf_lint_rules

flutter:
  uses-material-design: true

