name: keyboard_listener
version: "2.0.0"
description: Keyboard listener created only on Flutter
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/keyboard_listener"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: keyboard_listener
  hostUrl:
  separate_repo_url:
