name: bottom_navigation_bar
description: Bottom navigation bar
version: 0.0.1-dev.0
author:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tabnavigator:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-LLC
      path: packages/tabnavigator

  # testing mock
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: bottom_navigation_bar
  separate_repo_url:
  hostUrl:
