name: bottom_navigation_bar
version: "1.0.0"
description: Widget for simple switch content by selected item in bottom bar
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/bottom_navigation_bar"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter
  tabnavigator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
