name: surf_logger
version: "1.0.0"
description: "Logger for Dart & Flutter"
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/surf_logger"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  logger: ^1.0.0

dev_dependencies:
  coverage: ^1.0.0
  mockito: ^5.0.0
  surf_lint_rules: ^1.0.0
  test: ^1.16.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_validator:
  exclude:
    - "example/**"
  ignore:
    - coverage

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: surf_logger
  separate_repo_url:
  hostUrl:
