name: cat_facts
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  mwwm: ^2.0.0
  provider: ^5.0.0
  relation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.9.0

  integration_test:
    sdk: flutter

  mocktail: ^0.1.2

  surf_lint_rules: ^1.1.1-dev.0

flutter:
  uses-material-design: true
