name: auto_reload
description: a library that helps to perform actions with some periodicity
version: 0.0.1
author:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #connection
  connectivity: 0.4.6+2
