name: mwwm
description: Reflection of widget in a single entity
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #внутренние библиотеки
  injector:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: project-ROS-25
      path: injector

  #rx
  rxdart: 0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.7.0

flutter:
