name: tabnavigator
version: "0.0.1-dev.5"
description: Module can manage the tabs on the screen.
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/tabnavigator"

dependencies:
  flutter:
    sdk: flutter
  surf_util: "^0.0.1-dev.0"
  surf_lint_rules: "^0.0.1-dev.0"
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: tabnavigator
  separate_repo_url:
  hostUrl:
