name: surf_lint_rules
version: "0.0.1-dev.142"
description: |
  Lint rules for "Surf" company for Dart and Flutter projects. Like pedantic but stricter.
  
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/surf_lint_rules"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: surf_lint_rules
  separate_repo_url:
  hostUrl:
