name: surf_lint_rules
version: 1.3.0
description: Lint rules for "Surf" company for Dart and Flutter projects.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/surf_lint_rules"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  dart_code_metrics: ^4.0.0-dev.2
  flutter_lints: ^1.0.3

environment:
  sdk: ">=2.13.0 <3.0.0"
