name: mwwm
version: 1.1.1
description: |
  Software architecture pattern for teams with different sizes. Add possibility to work separately. Separate UI, presentation logic and business logic.

repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/mwwm"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
