name: surf_util
description: Common classes and util.
version: 0.0.1-dev.0
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger:
    path: ../logger

  relation:
    path: ../relation

  swipe_refresh:
    path: ../swipe_refresh

  surf_lint_rules:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: surf_util
  separate_repo_url:
  hostUrl:
