name: surf_util
version: 1.0.1
description: A library with set of common classes and utilities.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/surf_util"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
