name: surf_mwwm
version: 2.0.0
description: |
  Reflection of widget in a single entity. Includes: surf_injector, relation, mwwm, rxdart.
homepage: "https://github.com/surfstudio/SurfGear/tree/main/packages/surf_mwwm"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter
  mwwm: ^2.0.0-dev.1
  relation: ^4.0.0-dev.1
  rxdart: ^0.27.0
  surf_injector: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
