name: surf_mwwm
description: Reflection of widget in a single entity
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #inner packages
  injector:
    path: ../injector

  relation:
    path: ../relation

  mwwm:
    path: ../mwwm


  #rx
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.7.0

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: surf_mwwm
  separate_repo_url:
  hostUrl:
