name: surf_mwwm
version: "0.0.1-dev.1"
description: Reflection of widget in a single entity
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/surf_mwwm"

dependencies:
  flutter:
    sdk: flutter
  surf_injector: "^0.0.1-dev.0"
  relation: ^0.0.2
  mwwm: ^0.1.1
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: surf_mwwm
  separate_repo_url:
  hostUrl:
