name: ink_widget
description: Widget library with ink effect without problems with decoration for child.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules:
    path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: ink_widget
  hostUrl: