name: jitsi_meet_screen
description: Plugin to show JitsiMeetView as new native screen
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules:
    path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.surf.jitsi_meet_screen
        pluginClass: JitsiMeetScreenPlugin
      ios:
        pluginClass: JitsiMeetScreenPlugin

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: true
  path: jitsi_meet_screen
  hostUrl: