name: counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  relation:
    path: ../

dev_dependencies:
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
