name: ci
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pubspec_parse: 0.1.5
  yaml: 2.2.0
  pubspec_yaml: ^1.0.0+1
  yamlicious: ^0.1.0
  shell: ^1.0.1
  path: ^1.6.4
  plain_optional: 0.1.3
  args: ^1.5.2
  meta: ^1.1.8
  dio: ^3.0.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.12.0
  mockito: ^4.1.1
