name: datalist
version: "0.0.1-dev.0"
description: Implementation DataList in Flutter
repository: https://github.com/surfstudio/SurfGear/tree/dev/packages/datalist

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: ^0.0.1-dev.0
  collection: ^1.14.13
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version: 1
  is_plugin: false
  path: datalist
  separate_repo_url:
  hostUrl:
