name: datalist
version: 1.0.1-dev.1
description: Implementation DataList in Flutter
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/datalist"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  surf_lint_rules: ^1.0.0
  test: ^1.17.0

environment:
  sdk: ">=2.12.0 <3.0.0"
