name: swipe_refresh
version: "0.0.1-dev.9"
description: Widget for refresh by swipe.
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/swipe_refresh"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: "^0.0.1-dev.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: swipe_refresh
  separate_repo_url:
  hostUrl:
