name: swipe_refresh
description: Widget for refresh by swipe.
version: 0.0.1
author:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules:
    path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: swipe_refresh
  separate_repo_url:
  hostUrl:
