name: build surf_lint_rules
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/surf_lint_rules/**"
      - ".github/workflows/surf_lint_rules.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/surf_lint_rules
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Run dependency validator
        run: |
          flutter pub global activate dependency_validator
          flutter pub global run dependency_validator:dependency_validator
      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .
      - name: Run formatter
        run: flutter format --set-exit-if-changed .
  package-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/surf_lint_rules
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/surf_lint_rules
