name: build surf_lint_rules

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/surf_lint_rules/**"
      - ".github/workflows/surf_lint_rules.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: packages/surf_lint_rules

    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Prepare check our conventions âš™ï¸
        run: dart pub upgrade
        working-directory: tools/ci-cd

      - name: Check our conventions ğŸ”
        run: dart run ../../tools/ci-cd/bin/ci.dart check-dev-branch

      - name: Install dependencies âš™ï¸
        run: flutter pub get

      - name: Run dependency validator ğŸ”
        run: |
          flutter pub global activate dependency_validator
          flutter pub global run dependency_validator:dependency_validator

      - name: Run analyzer ğŸ”
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter ğŸ”
        run: flutter format --set-exit-if-changed .

  package-analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/surf_lint_rules

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Run package analyzer ğŸ”
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/surf_lint_rules
